var styles = {
	scrollView : {
		height : '11.44rem',
	},
	container : {
		display : 'flex',
		flexDirection : 'column',
		width : '7.5rem',
		deleteNext: "true",
		marginTop : '0.88rem',
		marginBottom : '1rem',
	},
	searchBar : {
		display : 'flex',
		position : 'fixed',
		height : '0.88rem',
		width : '6.9rem',
		top : 0,
		alignItems : 'center',
		flexDirection : 'row',
		backgroundColor : 'white',
		borderBottom : '0.01rem solid #f3f3f3',
		paddingLeft: '0.3rem',
		paddingRight: '0.3rem'
	},
	searchView : {
		display : 'flex',
		flexDirection : 'row',
		flex : 1,
		height : '0.56rem',
		borderRadius : '0.08rem',
		alignItems : 'center',
		backgroundColor : '#f0f0f0',
		opacity: 0.7
	},
	searchImg : {
		width : '0.32rem',
		height : '0.32rem',
		marginLeft : '0.18rem',
	},
	messageImg : {
		height : '0.4rem',
		width : '0.4rem',
	},
	messageLink: {
		height : '0.4rem',
		width : '0.4rem',
		marginLeft : '0.3rem',
	},
	viewDirection : {
		flexDirection : 'column',
	},
	goodsTypeItem : {
		flexDirection : 'column',
		borderTop : '0.16rem solid #f3f3f3',
		backgroundColor : 'white',
	},
	typeHeader : {
		display : 'flex',
		height : '0.6rem',
		alignItems : 'center',
		flexDirection : 'row',
		borderBottom : '0.01rem solid #f3f3f3',
	},
	typeFont : {
		fontSize : '0.24rem',
		marginLeft : '0.3rem',
		color : '#333333',
	},
	typeContent : {
		flex : 1,
		fontSize : '0.24rem',
		marginRight : '0.1rem',
		textAlign : 'right',
		color : '#999999',
	},
	goRightImg : {
		width : '0.14rem',
		height : '0.24rem',
		marginRight : '0.3rem',
	},
	typeView : {
		display : 'flex',
		flexDirection : 'row',
		flexWrap : 'wrap',
		backgroundColor : 'white',
	},
	brandsView : {
		display : 'flex',
		width : '2.47rem',
		height : '2.47rem',
		alignItems : 'center',
		justifyContent : 'center',
		borderBottom : '0.01rem solid #f3f3f3',
		borderRight : '0.01rem solid #f3f3f3',
	},
	brandsImg : {
		width : '2rem',
		height : '2rem',
	},
	typeInfo : {
		display : 'flex',
		width : '2.47rem',
		height : '2.47rem',
		flexDirection : 'column',
		alignItems : 'center',
		borderBottom : '0.01rem solid #f3f3f3',
		borderRight : '0.01rem solid #f3f3f3',
	},
	typeTitle : {
		marginTop : '0.4rem',
		fontSize : '0.24rem',
		color : '#333333',
	},
	typeImg : {
		marginTop : '0.3rem',
		width : '1.2rem',
		height : '1.2rem',
	},
	brands : {
		display : 'flex',
		height : '0.6rem',
		alignItems : 'center',
		flexDirection : 'row',
		borderBottom : '0.01rem solid #f3f3f3',
	},
	brandsHeader : {
		display : 'flex',
		height : '0.6rem',
		alignItems : 'center',
		borderTop : '0.16rem solid #f3f3f3',
		backgroundColor : 'white',
		borderBottom : '0.01rem solid #f3f3f3',
	},
	brandsTitle : {
		color : '#333333',
		fontSize : '0.24rem',
		marginLeft : '0.3rem',
	},
	global : {
		display : 'flex',
		backgroundColor : '#f3f3f3',
		height : '0.8rem',
		alignItems : 'center',
		borderBottom : '0.01rem solid #f3f3f3',
	},
	globalTitle : {
		color : '#333333',
		fontSize : '0.24rem',
		marginLeft : '0.3rem',
	},
	infoOutView: {
		display : 'flex',
		position : 'relative',
		width : '2.47rem',
		height : '2.47rem',
		flexDirection : 'column',
		alignItems : 'center',
		borderBottom : '0.01rem solid #f3f3f3',
		borderRight : '0.01rem solid #f3f3f3',
	},
	infoInsideImg: {
		width : '2.47rem',
		height : '2.47rem',
	},
	globalCountry : {
		color : 'white',
		fontSize : '0.36rem',
		position : 'absolute',
		width : '2.47rem',
		textAlign : 'center',
		top : '0.8rem',
	},
	globalCountryEng : {
		color : 'white',
		fontSize : '0.24rem',
		position : 'absolute',
		width : '2.47rem',
		textAlign : 'center',
		top : '1.3rem',
	},
}

module.exports = styles;
