/*
 * Name: StringResource.js
 * Creator: ZhangZhao
 * Create Time: 2016-08-23
 * Instruction: 字符串资源
 */

const STRING_RESOURCE = {
    consignee: '收货人   ',
    phoneNumber: '手机号码',
    detailAddress: '详细地址',
    moreThanFiveChinese: '不少于5个汉字',
    idCard: '身份证',
    customsNeed: '海关报关需要验证身份信息',
    saveAndUse: '保存并使用',
    saveAddress: '保存',
    confirmOrder: '确认订单',
    payWay: '支付方式',
    alipayPay: '支付宝支付',
    wechatPay: '微信支付',
    payableDetail: '应付明细',
    total: '总计：',
    goToPay: '去付款',
    totalGoodsPayable: '商品应付总计：￥',
    goodsTotalPrice: '商品总价：',
    activityDiscount: '活动优惠：',
    coupon: '优惠券：',
    freight: '运费：',
    taxation: '税费：',
    shoppingCart: '购物车',
    edit: '编辑',
    finish: '完成',
    settlement: '结算',
    delete: '删除',
    emptyInvalidGoods: '清空失效商品',
    invalid: '失效',
    checkAll: '全选',
    summation: '合计：',
    includeTaxation: '(含关税￥',
    excludeFreight: '，不含运费)',
    wareHouseTaxation: '本仓关税：',
    wareHouseTotalExTax: '本仓总计(不含税)：',
    shoppingCartNull: '购物车空空如也，去看看心仪的商品吧~',
    goShopping: '去购物',
    pleaseInputConsigneeMessage: '请输入收货人信息',
    pleaseInputCorrectPhoneNum: '请输入正确的手机号',
    pleaseInputCorrectAddMessage: '请输入正确的收货地址',
    pleaseInputCorrectIdNumber: '请输入正确的身份证号码',
    isLoadingWaitMinute: '加载中,请稍候...',
    addressListTitle: '我的收货地址',
    addAddressTitle: '新增收货地址',
    addressDetailTitle: '编辑收货人地址',
    addressEditorTitle: '编辑收货地址',
    confirmAddressTitle: '选择收货地址',
    couponCodeHint: '请输入有优惠券码',
    couponListTitle: '选择优惠券',
    couponExchange: '兑换',
    couponValueTime: '有效期：',
    couponTitle: '我的优惠券',
    localArea: '所在地区',
    setDetailAddress: '设为默认地址',
    search: '搜索',
    searchKeyWords: '搜索关键字',
    confirmPayment: '确认付款',
    confirmPay: '确认支付',
    orderHasBeenSubmit: '订单已提交',
    pleaseFinishPaymentIn24Hours: '请在24小时内完成付款',
    amountPaid: '已付金额：',
    payWayDot: '支付方式：',
    checkOrders: '查看订单',
    backToHome: '返回首页',
    paymentSuccess: '支付成功',
    hotSearchKeyWords: '热门搜索',
    latelySearchKeyWords: '最近搜索'
};

module.exports = STRING_RESOURCE;
