//home
export const FETCH_ACTIVITY = "FETCH_ACTIVITY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_BANNER = "FETCH_BANNER";
export const FETCH_GOOD_LIST = "FETCH_GOOD_LIST";
export const FETCH_RECOMMEND = "FETCH_RECOMMEND";

//login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//tab
export const TAB_HOME_CLICK = "TAB_HOME_CLICK";
export const TAB_SHOP_CLICK = "TAB_SHOP_CLICK";
export const TAB_SETTING_CLICK = "TAB_SETTING_CLICK";
export const TAB_CLASSIFY_CLICK = "TAB_CLASSIFY_CLICK";

//我的收藏
export const COLLECTION = "COLLECTION";
export const MORECOLLECTION = "MORECOLLECTION";
export const COLLECTIONGOODS = 'COLLECTIONGOODS';
//我的订单
export const MYALLORDER = "MYALLORDER";
export const WAITPAIDORDER = "WAITPAIDORDER";
export const WAITSENDORDER = "WAITSENDORDER";
export const WAITRECEIVEORDER = "WAITRECEIVEORDER";
export const WAITCOMMENTORDER = "WAITCOMMENTORDER";
export const ORDERDETAILDATA = "ORDERDETAILDATA";
//订单详情
export const USERORDERDETAIL = 'USERORDERDETAIL';

//注册
export const PROTOCOLIMG  = "PROTOCOLIMG";
export const PROTOCOLIMGED  = "PROTOCOLIMGED";
//Shopping cart
export const GOT_SHOPPINGCART_DATA = 'GOT_SHOPPINGCART_DATA';
export const CHECKBOOX_CLICKED = 'CHECKBOOX_CLICKED';
export const START_LOADING_DATA = 'START_LOADING_DATA';
export const END_LOADING_DATA = 'END_LOADING_DATA';


//confirm order
export const GOT_CONFIRM_ORDER_DATA = 'GOT_CONFIRM_ORDER_DATA';
export const START_LOADING_DATA_MS = 'START_LOADING_DATA_MS';
export const END_LOADING_DATA_MS = 'END_LOADING_DATA_MS';
export const SHOPPINGCART_SETTLEMENT = 'SHOPPINGCART_SETTLEMENT';
export const IMMEDIATELY_BUY = 'IMMEDIATELY_BUY';
export const INIT_STATE_MS = 'INIT_STATE_MS';

//个人中心 我的收获地址
export const ADDRESSLIST = "ADDRESSLIST";
export const ADDRESSLIST_DEFAULT = "ADDRESSLIST_DEFAULT";
export const CACHE_CHOOSED_ADDRESS = 'CACHE_CHOOSED_ADDRESS';

//搜索

export const SEARCH_DATA = "SEARCH_DATA";
export const GETGOODS_DATA = "GETGOODS_DATA";
export const LOADMOREGOODS = "LOADMOREGOODS";
export const ADDRESSDETAIL = "ADDRESSDETAIL";
export const ADDRESSDETAIL_ADD = "ADDRESSDETAIL_ADD";
export const ADDRESSDETAIL_CHANGE = "ADDRESSDETAIL_CHANGE";

//分类
export const GOT_CLASSIFY_DATA = 'GOT_CLASSIFY_DATA';
//商品详情
export const GOT_GOODSDETAILDATA_DATA = 'GOT_GOODSDETAILDATA_DATA';
//购物车数量
export const GOT_CARTCOUNT = 'GOT_CARTCOUNT';
//添加到购物车
export const PUSH_ITEMTOCART = 'PUSH_ITEMTOCART';
//立即添加购物车
export const DIRECTCHANGE = 'DIRECTCHANGE';
//商品列表
export const PRODUCTLIST = "PRODUCTLIST";

//品牌详情
export const BRANDDETAIL = "BRANDDETAIL";
export const HOTBRANDDATA = "HOTBRANDDATA";

//确认订单  兑换优惠券
export const COUPONCODE = "COUPONCODE";
export const COUPONID = "COUPONID";
//个人中兴  优惠券列表
export const COUPONLIST = "COUPONLIST";
export const COUPONINFO = "COUPONINFO";

//传值方法
export const SEND_MESSAGE = 'SEND_MESSAGE';

//获取省市县
export const PROVINCELIST = "PROVINCELIST";
export const CITYLIST = "CITYLIST";
export const COUNTYLIST = "COUNTYLIST";